include(":player:public")
include(":player")
include(":shared")
include(":di")
include(":newsfeed:fake")
include(":newsfeed:public")
include(":repository:fake")
include(":repository:public")
include(":repository")
include(":newsfeed")
include(":networkdatasource:fake")
include(":networkdatasource")
include(":model")
include(":datasource")
include(":apimodel")
include(":api:fakeapi")
include(":api")
rootProject.buildFileName = "build.gradle.kts"

include(":app")
